version: '3.4'

services:
  vortex_l4d2_db:
    container_name: vortex_l4d2_db
    image: mysql:8.3
    ports:
      - "3308:3308"
    env_file:
      - .env
    expose:
      - ${MYSQL_TCP_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
    - vortex-l4d2-database:/var/lib/mysql
  
  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - vortex-l4d2-redis:/data
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
      - --maxmemory 256mb 
      - --save 900 1 
      - --save 300 10 
      - --save 60 1000
    
  l4d2vortexapi:
    container_name: l4d2vortexapi
    links:
      - "vortex_l4d2_db"
    image: l4d2vortexapi
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 3005:3005
    restart: on-failure
    depends_on:
      - vortex_l4d2_db
      - redis
  
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - celery-data:/user/src/app
    command:  celery -A src.celery.tasks.celery worker --loglevel=info
    depends_on:
      - vortex_l4d2_db
      - l4d2vortexapi
      - redis
    
  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: celery -A src.celery.tasks.celery beat --loglevel=info
    volumes:
      - celery-data:/user/src/app
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555 --basic-auth=root:${FLOWER_PASSWORD}
    ports:
    - 5555:5555
    depends_on:
      - worker
      - redis

  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - "vortex_l4d2_db"
    ports:
      - 3337:80
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - vortex_l4d2_db

volumes:
  vortex-l4d2-database:
  vortex-l4d2-redis:
  celery-data: