version: '3.4'

services:
  vortex_l4d2_db:
    container_name: vortex_l4d2_db
    image: mysql:8.3
    ports:
      - "3308:3308"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
    - vortex-l4d2-database:/var/lib/mysql
    
  l4d2vortexapi:
    container_name: l4d2vortexapi
    links:
      - "vortex_l4d2_db"
    image: l4d2vortexapi
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 3005:3005
    restart: on-failure
  
  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - "vortex_l4d2_db"
    ports:
      - 3337:80
    env_file:
      - .env
    restart: unless-stopped

volumes:
  vortex-l4d2-database: