"""empty message

Revision ID: 00a046e5a18a
Revises: b56f326616a8
Create Date: 2025-04-22 08:43:40.977325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a046e5a18a'
down_revision: Union[str, None] = 'b56f326616a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chatlog_nickname', 'chatLogs', ['nickname'], unique=False)
    op.create_index('idx_chatlog_server', 'chatLogs', ['server'], unique=False)
    op.create_index('idx_chatlog_steamid', 'chatLogs', ['steamId'], unique=False)
    op.create_index('idx_chatlog_time', 'chatLogs', ['time'], unique=False)
    op.create_index('idx_privstatus_active', 'privilegeStatus', ['activeUntil'], unique=False)
    op.create_index('idx_privstatus_user_priv', 'privilegeStatus', ['userId', 'privilegeId'], unique=False)
    op.create_index('idx_discordlink_discordid', 'steamDiscordLink', ['discordId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_discordlink_discordid', table_name='steamDiscordLink')
    op.drop_index('idx_privstatus_user_priv', table_name='privilegeStatus')
    op.drop_index('idx_privstatus_active', table_name='privilegeStatus')
    op.drop_index('idx_chatlog_time', table_name='chatLogs')
    op.drop_index('idx_chatlog_steamid', table_name='chatLogs')
    op.drop_index('idx_chatlog_server', table_name='chatLogs')
    op.drop_index('idx_chatlog_nickname', table_name='chatLogs')
    # ### end Alembic commands ###
