"""New statistics

Revision ID: 134a3207886d
Revises: d90b095e7eb3
Create Date: 2025-05-22 11:34:02.951603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134a3207886d'
down_revision: Union[str, None] = 'd90b095e7eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('st_player_base',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('last_nickname', sa.String(length=128), nullable=True),
    sa.Column('last_online', sa.String(length=32), nullable=True),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('last_country', sa.String(length=64), nullable=True),
    sa.Column('last_city', sa.String(length=64), nullable=True),
    sa.Column('last_region', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_st_player_base_userid', 'st_player_base', ['userId'], unique=True)
    op.create_table('st_player_hits',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('NULL_HITBOX', sa.Integer(), nullable=False),
    sa.Column('HEAD', sa.Integer(), nullable=False),
    sa.Column('CHEST', sa.Integer(), nullable=False),
    sa.Column('STOMACH', sa.Integer(), nullable=False),
    sa.Column('LEFT_ARM', sa.Integer(), nullable=False),
    sa.Column('RIGHT_ARM', sa.Integer(), nullable=False),
    sa.Column('LEFT_LEG', sa.Integer(), nullable=False),
    sa.Column('RIGHT_LEG', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_st_player_hits_userid', 'st_player_hits', ['userId'], unique=True)
    op.create_table('st_player_kills',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('survivor_killed', sa.Integer(), nullable=False),
    sa.Column('infected_killed', sa.Integer(), nullable=False),
    sa.Column('tank_killed', sa.Integer(), nullable=False),
    sa.Column('boomer_killed', sa.Integer(), nullable=False),
    sa.Column('hunter_killed', sa.Integer(), nullable=False),
    sa.Column('charger_killed', sa.Integer(), nullable=False),
    sa.Column('spitter_killed', sa.Integer(), nullable=False),
    sa.Column('jockey_killed', sa.Integer(), nullable=False),
    sa.Column('witch_killed', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_st_player_kills_userid', 'st_player_kills', ['userId'], unique=True)
    op.create_table('st_player_shots',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('player_fire', sa.Integer(), nullable=False),
    sa.Column('player_hits', sa.Integer(), nullable=False),
    sa.Column('player_heads', sa.Integer(), nullable=False),
    sa.Column('player_damage', sa.Integer(), nullable=False),
    sa.Column('player_hurt', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_st_player_shots_userid', 'st_player_shots', ['userId'], unique=True)
    op.create_table('st_player_weapon',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('pistol', sa.Integer(), nullable=False),
    sa.Column('pistol_magnum', sa.Integer(), nullable=False),
    sa.Column('autoshotgun', sa.Integer(), nullable=False),
    sa.Column('shotgun_chrome', sa.Integer(), nullable=False),
    sa.Column('pumpshotgun', sa.Integer(), nullable=False),
    sa.Column('shotgun_spas', sa.Integer(), nullable=False),
    sa.Column('smg', sa.Integer(), nullable=False),
    sa.Column('smg_mp5', sa.Integer(), nullable=False),
    sa.Column('smg_silenced', sa.Integer(), nullable=False),
    sa.Column('rifle_ak47', sa.Integer(), nullable=False),
    sa.Column('rifle_sg552', sa.Integer(), nullable=False),
    sa.Column('rifle', sa.Integer(), nullable=False),
    sa.Column('rifle_m60', sa.Integer(), nullable=False),
    sa.Column('rifle_desert', sa.Integer(), nullable=False),
    sa.Column('hunting_rifle', sa.Integer(), nullable=False),
    sa.Column('sniper_military', sa.Integer(), nullable=False),
    sa.Column('sniper_awp', sa.Integer(), nullable=False),
    sa.Column('sniper_scout', sa.Integer(), nullable=False),
    sa.Column('weapon_grenade_launcher', sa.Integer(), nullable=False),
    sa.Column('molotov', sa.Integer(), nullable=False),
    sa.Column('pipe_bomb', sa.Integer(), nullable=False),
    sa.Column('vomitjar', sa.Integer(), nullable=False),
    sa.Column('melee', sa.Integer(), nullable=False),
    sa.Column('baseball_bat', sa.Integer(), nullable=False),
    sa.Column('cricket_bat', sa.Integer(), nullable=False),
    sa.Column('crowbar', sa.Integer(), nullable=False),
    sa.Column('electric_guitar', sa.Integer(), nullable=False),
    sa.Column('fireaxe', sa.Integer(), nullable=False),
    sa.Column('frying_pan', sa.Integer(), nullable=False),
    sa.Column('katana', sa.Integer(), nullable=False),
    sa.Column('knife', sa.Integer(), nullable=False),
    sa.Column('machete', sa.Integer(), nullable=False),
    sa.Column('tonfa', sa.Integer(), nullable=False),
    sa.Column('pain_pills', sa.Integer(), nullable=False),
    sa.Column('adrenaline', sa.Integer(), nullable=False),
    sa.Column('defibrillator', sa.Integer(), nullable=False),
    sa.Column('first_aid_kit', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_st_player_weapon_userid', 'st_player_weapon', ['userId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_st_player_weapon_userid', table_name='st_player_weapon')
    op.drop_table('st_player_weapon')
    op.drop_index('idx_st_player_shots_userid', table_name='st_player_shots')
    op.drop_table('st_player_shots')
    op.drop_index('idx_st_player_kills_userid', table_name='st_player_kills')
    op.drop_table('st_player_kills')
    op.drop_index('idx_st_player_hits_userid', table_name='st_player_hits')
    op.drop_table('st_player_hits')
    op.drop_index('idx_st_player_base_userid', table_name='st_player_base')
    op.drop_table('st_player_base')
    # ### end Alembic commands ###
