"""New Server Status

Revision ID: 1ce2ced7c9d9
Revises: 9e75cc1d6ab7
Create Date: 2025-05-06 10:55:55.406729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ce2ced7c9d9'
down_revision: Union[str, None] = '9e75cc1d6ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_status',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('map', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('max_slots', sa.Integer(), nullable=False),
    sa.Column('current_players', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_server_ip_port', 'server_status', ['ip', 'port'], unique=True)
    op.create_table('server_player',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('connection_time', sa.Float(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_status.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_server_player_server', 'server_player', ['server_id'], unique=False)
    op.create_index('idx_server_player_steamid', 'server_player', ['steam_id'], unique=False)
    op.create_index('idx_server_player_unique', 'server_player', ['server_id', 'steam_id'], unique=True)
    op.drop_table('serverStats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serverStats',
    sa.Column('time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('players', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maxPlayers', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('map', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('ping', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('port', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index('idx_server_player_unique', table_name='server_player')
    op.drop_index('idx_server_player_steamid', table_name='server_player')
    op.drop_index('idx_server_player_server', table_name='server_player')
    op.drop_table('server_player')
    op.drop_index('idx_server_ip_port', table_name='server_status')
    op.drop_table('server_status')
    # ### end Alembic commands ###
