"""empty message

Revision ID: 35c7d4dd0cd1
Revises: 
Create Date: 2024-07-27 22:20:53.675390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c7d4dd0cd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatLogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steamId', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('server', sa.String(length=32), nullable=False),
    sa.Column('team', sa.SmallInteger(), nullable=False),
    sa.Column('chatTeam', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privilegeType',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accessLevel', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steamId', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customPrefix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(length=64), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perkSet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survivorPerk1', sa.String(length=64), nullable=False),
    sa.Column('survivorPerk2', sa.String(length=64), nullable=False),
    sa.Column('survivorPerk3', sa.String(length=64), nullable=False),
    sa.Column('survivorPerk4', sa.String(length=64), nullable=False),
    sa.Column('boomerPerk', sa.String(length=64), nullable=False),
    sa.Column('smokerPerk', sa.String(length=64), nullable=False),
    sa.Column('hunterPerk', sa.String(length=64), nullable=False),
    sa.Column('jockeyPerk', sa.String(length=64), nullable=False),
    sa.Column('spitterPerk', sa.String(length=64), nullable=False),
    sa.Column('chargerPerk', sa.String(length=64), nullable=False),
    sa.Column('tankPerk', sa.String(length=64), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privilegeStatus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('privilegeId', sa.Integer(), nullable=False),
    sa.Column('activeUntil', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['privilegeId'], ['privilegeType.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steamDiscordLink',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('discordId', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('welcomePhrase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phrase', sa.String(length=256), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duplexTransaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sourceId', sa.Integer(), nullable=False),
    sa.Column('targetId', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sourceId'], ['balance.id'], ),
    sa.ForeignKeyConstraint(['targetId'], ['balance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balanceId', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['balanceId'], ['balance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('duplexTransaction')
    op.drop_table('welcomePhrase')
    op.drop_table('steamDiscordLink')
    op.drop_table('privilegeStatus')
    op.drop_table('perkSet')
    op.drop_table('customPrefix')
    op.drop_table('balance')
    op.drop_table('authToken')
    op.drop_table('user')
    op.drop_table('privilegeType')
    op.drop_table('chatLogs')
    # ### end Alembic commands ###
