"""fix_names

Revision ID: 37cc1db5a764
Revises: a036f09d84cf
Create Date: 2025-01-24 21:23:57.686161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cc1db5a764'
down_revision: Union[str, None] = 'a036f09d84cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('players_reports_ibfk_1', 'players_reports', type_='foreignkey')
    op.create_foreign_key(None, 'players_reports', 'violation_types', ['violation_type_id'], ['type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players_reports', type_='foreignkey')
    op.create_foreign_key('players_reports_ibfk_1', 'players_reports', 'violation_types', ['violation_type_id'], ['id'])
    # ### end Alembic commands ###
