"""items api

Revision ID: 407d5aaa2382
Revises: 91c9bdba531e
Create Date: 2024-08-10 15:59:23.392852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407d5aaa2382'
down_revision: Union[str, None] = '91c9bdba531e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('l4d2Item',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('command', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emptyDrop',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privilegeItem',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('privilegeTypeId', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['privilegeTypeId'], ['privilegeType.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userInventory',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('activeUntil', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['itemId'], ['l4d2Item.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=True),
    sa.Column('privilegeItemId', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['itemId'], ['l4d2Item.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['privilegeItemId'], ['privilegeItem.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simpleQuest',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('rewardId', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['rewardId'], ['reward.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailyQuest',
    sa.Column('activeUntil', sa.DateTime(timezone=True), nullable=False),
    sa.Column('curProgress', sa.Integer(), nullable=False),
    sa.Column('maxProgress', sa.Integer(), nullable=False),
    sa.Column('questId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['questId'], ['simpleQuest.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailyQuests_Rewards',
    sa.Column('dailyQuestId', sa.Integer(), nullable=False),
    sa.Column('rewardId', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['dailyQuestId'], ['dailyQuest.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['rewardId'], ['reward.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailyQuests_Rewards')
    op.drop_table('dailyQuest')
    op.drop_table('simpleQuest')
    op.drop_table('reward')
    op.drop_table('userInventory')
    op.drop_table('privilegeItem')
    op.drop_table('emptyDrop')
    op.drop_table('l4d2Item')
    # ### end Alembic commands ###
