"""New line

Revision ID: 42a3b02bdf93
Revises: 134a3207886d
Create Date: 2025-05-22 13:17:55.952073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a3b02bdf93'
down_revision: Union[str, None] = '134a3207886d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('st_player_shots', sa.Column('player_death', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('st_player_shots', 'player_death')
    # ### end Alembic commands ###
