"""Added score system

Revision ID: 5279727ad1fa
Revises: b2004e3c7555
Create Date: 2024-07-29 14:17:46.467566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5279727ad1fa'
down_revision: Union[str, None] = 'b2004e3c7555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playSession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('timeFrom', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeTo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roundScore',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('agression', sa.Integer(), nullable=False),
    sa.Column('support', sa.Integer(), nullable=False),
    sa.Column('perks', sa.Integer(), nullable=False),
    sa.Column('team', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoreSeason',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('agression', sa.Integer(), nullable=False),
    sa.Column('support', sa.Integer(), nullable=False),
    sa.Column('perks', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoreSeason')
    op.drop_table('roundScore')
    op.drop_table('playSession')
    # ### end Alembic commands ###
