"""Add indexes to RoundScore table

Revision ID: 784a53e24a27
Revises: 4e1434681b57
Create Date: 2025-04-30 16:25:18.964157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784a53e24a27'
down_revision: Union[str, None] = '4e1434681b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_roundscore_scores', 'roundScore', ['agression', 'support', 'perks'], unique=False)
    op.create_index('idx_roundscore_userid', 'roundScore', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_roundscore_userid', table_name='roundScore')
    op.drop_index('idx_roundscore_scores', table_name='roundScore')
    # ### end Alembic commands ###
