"""update player music url field

Revision ID: 8e4ea0d59e2a
Revises: b1b9de2a2135
Create Date: 2025-01-20 12:14:56.906149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4ea0d59e2a'
down_revision: Union[str, None] = 'b1b9de2a2135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
