"""giveaway cascade 2

Revision ID: 91c9bdba531e
Revises: d0274628ead3
Create Date: 2024-08-06 21:54:50.124817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c9bdba531e'
down_revision: Union[str, None] = 'd0274628ead3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('giveawayUse_ibfk_1', 'giveawayUse', type_='foreignkey')
    op.create_foreign_key(None, 'giveawayUse', 'giveaway', ['giveawayId'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'giveawayUse', type_='foreignkey')
    op.create_foreign_key('giveawayUse_ibfk_1', 'giveawayUse', 'giveaway', ['giveawayId'], ['id'])
    # ### end Alembic commands ###
