"""Adde serverStats.sid

Revision ID: 93c52603d1c8
Revises: 6fda241be9b9
Create Date: 2024-08-20 20:43:02.549237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c52603d1c8'
down_revision: Union[str, None] = '6fda241be9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serverStats', sa.Column('sid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serverStats', 'sid')
    # ### end Alembic commands ###
