"""Add Soundpad

Revision ID: 9e75cc1d6ab7
Revises: 5570f61b5a4a
Create Date: 2025-05-04 02:14:12.565084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e75cc1d6ab7'
down_revision: Union[str, None] = '5570f61b5a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_sounds', sa.Column('cooldown', sa.Float(), nullable=False))
    op.drop_constraint('player_sounds_ibfk_1', 'player_sounds', type_='foreignkey')
    op.drop_column('player_sounds', 'userId')
    op.drop_column('player_sounds', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_sounds', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('player_sounds', sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('player_sounds_ibfk_1', 'player_sounds', 'user', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_column('player_sounds', 'cooldown')
    # ### end Alembic commands ###
