"""add_name_en

Revision ID: a036f09d84cf
Revises: 47b1b324814b
Create Date: 2025-01-24 21:14:06.951981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a036f09d84cf'
down_revision: Union[str, None] = '47b1b324814b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation_types', sa.Column('name_ru', sa.String(length=64), nullable=False))
    op.add_column('violation_types', sa.Column('name_en', sa.String(length=64), nullable=False))
    op.drop_column('violation_types', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation_types', sa.Column('name', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('violation_types', 'name_en')
    op.drop_column('violation_types', 'name_ru')
    # ### end Alembic commands ###
