"""add url to player music

Revision ID: b1b9de2a2135
Revises: 8e6c09064e97
Create Date: 2025-01-19 17:16:20.007340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b9de2a2135'
down_revision: Union[str, None] = '8e6c09064e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_music', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_music', 'url')
    # ### end Alembic commands ###
