"""Recreate reports tables

Revision ID: b56f326616a8
Revises: 37cc1db5a764
Create Date: 2025-01-24 21:26:27.195962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56f326616a8'
down_revision: Union[str, None] = '37cc1db5a764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_id')
    )
    op.create_table('players_reports',
    sa.Column('reporter_name', sa.String(length=64), nullable=False),
    sa.Column('reporter_id64', sa.String(length=64), nullable=False),
    sa.Column('reporter_team', sa.SmallInteger(), nullable=False),
    sa.Column('suspect_name', sa.String(length=64), nullable=False),
    sa.Column('suspect_id64', sa.String(length=64), nullable=False),
    sa.Column('suspect_team', sa.SmallInteger(), nullable=False),
    sa.Column('violation_type_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('map_name', sa.String(length=32), nullable=False),
    sa.Column('demo_path', sa.String(length=256), nullable=True),
    sa.Column('game_time', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('admin_id64', sa.String(length=64), nullable=True),
    sa.Column('resolution_note', sa.String(length=512), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['violation_type_id'], ['violation_types.type_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players_reports')
    op.drop_table('violation_types')
    # ### end Alembic commands ###
