"""Add smoker_killed to st_player_kills table

Revision ID: b9139277e000
Revises: 42a3b02bdf93
Create Date: 2025-05-22 16:52:44.968500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9139277e000'
down_revision: Union[str, None] = '42a3b02bdf93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('st_player_kills', sa.Column('smoker_killed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('st_player_kills', 'smoker_killed')
    # ### end Alembic commands ###
