"""autoconnection queue

Revision ID: d90b095e7eb3
Revises: 1ce2ced7c9d9
Create Date: 2025-05-06 16:09:40.030775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90b095e7eb3'
down_revision: Union[str, None] = '1ce2ced7c9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
