"""MaybeFix

Revision ID: dde565559765
Revises: b9139277e000
Create Date: 2025-05-24 21:17:14.070213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dde565559765'
down_revision: Union[str, None] = 'b9139277e000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_seen', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('server_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_status.id'], name=op.f('user_activity_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('user_activity_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_user_activity_userid'), 'user_activity', ['userId'], unique=True)
    # ### end Alembic commands ###
